apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "grafana-service"
    port: 3000
    targetPort: 3000
    nodePort: 31003
  selector:
    app: grafana
